"""phase 3 baseline

Revision ID: a51e64afbd0f
Revises: 
Create Date: 2026-06-03 11:20:14.922698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a51e64afbd0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_number', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('vin', sa.Text(), nullable=False),
    sa.Column('vehicle_snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('incident_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=False),
    sa.Column('assigned_adjuster_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("current_status IN ('submitted', 'triaged', 'investigating', 'settled', 'closed', 'denied')", name='claims_current_status_enum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_status_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('submitted', 'triaged', 'investigating', 'settled', 'closed', 'denied')", name='claim_status_history_from_status_enum'),
    sa.CheckConstraint("to_status IN ('submitted', 'triaged', 'investigating', 'settled', 'closed', 'denied')", name='claim_status_history_to_status_enum'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_status_history')
    op.drop_table('claims')
    # ### end Alembic commands ###
